name: Aproxia Windows Build

on:
  workflow_dispatch:
  push:
    branches:
      - aproxia-v1
    paths-ignore:
      - "docs/**"
      - "README.md"
      - "res/**"
      - "appimage/**"
      - "flatpak/**"

jobs:
  run-ci:
    uses: ./.github/workflows/flutter-build.yml
    with:
      upload-artifact: true
      upload-tag: "aproxia-v1-preview"
